[package]
name = "ryn"
version = "1.0.0-alpha"
edition = "2024"

[dependencies]
chrono = "0.4.40"
colored = "3.0.0"
ctrlc = "3.4.5"
dirs = "6.0.0"
hostname = "0.4.0"
humantime = "2.2.0"
os_pipe = "1.2.1"
rustyline = "15.0.0"
